version: "3.3"

# NETWORKS
networks:
    default:
        driver: bridge

# # VOLUMES
# volumes:
#     # Sonarr Downloads
#     sonarr_downloads:
#         # name: sonarr_downloads
#         driver: local
#         driver_opts:
#           type: none
#           device: /mnt/animexescure/sonarr_downloads
#           o: bind

services:
  ethminer:
    image: xescure/ethminer
    build:
      context: .
      dockerfile: Dockerfile
      
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              # count: 1
              device_ids:
                - '0'

    # runtime: nvidia


    command: -P stratum://0xB635F798fa79Fd180315C7e599Fa0bcF375D972b.the-machine@eu1.ethermine.org:4444
